WebShoe/WebShoe/Controllers/DangNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebShoe.Models;
using System.Web.Mvc;
using System.Web.Security;

namespace WebShoe.Controllers
{
    public class DangNhapController : Controller
    {
       CT25Team25Entities db;
        public DangNhapController()
        {
            db = new CT25Team25Entities();
        }
        // GET: DangNhap
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index(Models.KhachHang model)
        {
            using (var context = new CT25Team25Entities())
            {
                var account = context.KhachHangs.Where(acc => acc.USERNAME == model.USERNAME && acc.PASSWORD == model.PASSWORD).FirstOrDefault();
                bool isValid = context.KhachHangs.Any(x => x.USERNAME == model.USERNAME
                && x.PASSWORD == model.PASSWORD);
                if (isValid)
                {
                    Session["MaKH"] = account.MaKH;
                    Session["TenKH"] = account.TenKH;
                    Session["USERNAME"] = account.USERNAME;
                    Session["PASSWORD"] = account.PASSWORD;
                    FormsAuthentication.SetAuthCookie(model.USERNAME, false);
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", "Invalid username or password !!!");
            Session["Message"] = "Sai thông tin tài khoản hoặc mật khẩu !!!";
            return View();
        }
        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebShoe/WebShoe/Controllers/GioHangsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShoe.Models;

namespace WebShoe.Controllers
{
    public class GioHangsController : Controller
    {
        // GET: GioHangs
        CT25Team25Entities db = new CT25Team25Entities();
        private List<DonHang> cart = null;
        public GioHangsController()
        {
            var Session = System.Web.HttpContext.Current.Session;
            if (Session["cart"] != null)
                cart = Session["cart"] as List<DonHang>;
            else
            {
                cart = new List<DonHang>();
                Session["cart"] = cart;
            }
        }

        // GET: Cart
        public ActionResult Index()
        {
            var hashtable = new Hashtable();
            foreach (var ChitietDH in cart)
            {
                if (hashtable[ChitietDH.MaSP] != null)
                {
                    (hashtable[ChitietDH.MaSP] as DonHang).SoLuong += ChitietDH.SoLuong;
                }
                else
                {
                    hashtable[ChitietDH.MaSP] = ChitietDH;
                }
            }
            cart.Clear();
            foreach (DonHang chitietDH in hashtable.Values)
            {
                cart.Add(chitietDH);
            }
            ViewBag.Success = "Không có sản phẩm nào trong giỏ hàng";
            return View(cart);
        }

        [HttpPost]
        public ActionResult AddtoCart(int productid, int soluong = 1)
        {
            var product = db.SanPhams.Find(productid);
            cart.Add(new DonHang
            {
                SanPham = product,
                SoLuong = soluong,
            });
            return RedirectToAction("Index");
        }

        public ActionResult UpdateCart([Microsoft.AspNetCore.Mvc.FromForm] int productid, [Microsoft.AspNetCore.Mvc.FromForm] int soluong)
        {
            cart = (List<DonHang>)Session["cart"];
            var product = cart.Find(p => p.SanPham.MaSP == productid);
            if (product != null)
            {
                product.SoLuong = soluong;
            }
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

        public ActionResult xoaSP(int id)
        {
            cart = (List<DonHang>)Session["cart"];
            var product = cart.Find(p => p.SanPham.MaSP == id);
            if (product != null)
            {
                cart.Remove(product);
            }
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddOrder(FormCollection fc)
        {
            int orderid = 0;
            cart = Session["cart"] as List<DonHang>;
            DonHang dh = new DonHang()
            {
                KhachHang_ID = Convert.ToInt32(fc["MaKH"]),
                TENKH = fc["TenKH"],
                DiaChi = fc["diachi"],
                PHONE = fc["sdt"],
                
                ORDERDATE = DateTime.Now,
                
                TongTien = Convert.ToDouble(fc["thanhtien"])
            };
            db.DonHangs.Add(dh);
            db.SaveChanges();
            orderid = dh.MaDH;
            foreach (var item in cart)
            {
                ChiTietGioHang chitiet = new ChiTietGioHang()
                {
                    MaCTGH = orderid,
                  
                    SanPham_ID = item.SanPham.MaSP,
                   
                    TenSP = item.SanPham.TenSP,
                    
                };

                db.ChiTietGioHangs.Add(chitiet);
                db.SaveChanges();
            }
            Session["cart"] = null;
            return RedirectToAction("OrderSuccess");
        }
        public ActionResult OrderSuccess()
        {

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebShoe/WebShoe/Views/Shared/_LayoutPage.cshtml
    @using WebShoe.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <title>WELLCOM TO THE SHOP SHOES MEOMUN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Fashion Club Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- css -->
    <link href="@Url.Content("~/CSS/bootstrap.css")" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/CSS/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/CSS/font-awesome.min.css" type="text/css" media="all" />
    <!--// css -->
    <!-- font -->
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!-- //font -->
    <script src="@Url.Content("~/js/jquery-1.11.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/bootstrap.js")" type="text/javascript"></script>
    <script defer src="@Url.Content("~/js/jquery.flexslider.js")"></script>
    <link rel="stylesheet" href="~/CSS/flexslider.css" type="text/css" media="screen" />
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                controlNav: "thumbnails"
            });
        });
    </script>
    <!--flex slider-->
    <script src="~/js/imagezoom.js"></script>
    <!-- //js -->

</head>
<body>
    <div class="header-top-w3layouts">
        <div class="container">
            <div class="col-md-6 logo-w3">
                <a href="@Url.Action("Index","Home")">
                    <h1>
                        <font face="aria-label">MEOMUN</font>
                        <span>SHOP</span>
                    </h1>
                </a>
            </div>
            <div class="dropdown">

                <div class="col-sm-4">

                    @if (Session["TenKH"] != null)
                    {
                        <i class="glyphicon glyphicon-user"></i>
                        <span style="font-size:11px;">Tài khoản</span>
                        <p id="Hello_Text">@Session["TenKH"].ToString()</p>

                        <div class="dropdown-menu">

                            <a href="@Url.Action("Index", "DangKi")">
                                Thông tin tài khoản
                            </a><br />
                            <a href="@Url.Action("LogOut", "DangNhap")" id="Button_LogOut">Đăng Xuất</a>
                        </div>
                    }
                    else if (Session["USERNAME"] != null && Session["TenKH"] == null)
                    {
                        <p id="Hello_Text">Hello</p>
                        <a href="@Url.Action("LogOut", "DangNhap")" id="Button_LogOut">Đăng Xuất</a>
                    }
                    else
                    {
                        <ul class="top_button_section">
                            <li>
                                <a class="login-bt active" href="~/DangNhap/Index">Đăng Nhập</a>
                            </li>
                            <li><a class="login-bt" href=@Url.Action("Index","DangKi")>Đăng Ký</a></li>
                        </ul>
                    }


                </div>
            </div>
            <div class="col-md-6 phone-w3l">
                <ul>
                    <li><span class="glyphicon glyphicon-earphone" aria-hidden="false"></span></li>
                    <li>+18045403380</li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="header-bot +18045403380
tom-w3ls">
        <div class="container">
            <div class="col-md-7 navigation-agileits">
                <nav class="navbar navbar-default">
                    <div class="navbar-header nav_2">
                        <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                            <span class="sr-only">Chuyển đổi hướng điều hành</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                        <ul class="nav navbar-nav ">
                            <li><a href="~/Home" class="hyper"><span>Trang Chủ</span></a></li>

                            <li><a href="~/SanPhams" class="hyper"><span>Sản Phẩm</span></a></li>
                            <li><a href="~/Home/About" class="hyper"><span>Thông tin</span></a></li>
                            <li><a href="~/Home/Contact" class="hyper"><span>Đánh Giá</span></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
            <script>
                $(document).ready(function () {
                    $(".dropdown").hover(
                        function () {
                            $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                            $(this).toggleClass('open');
                        },
                        function () {
                            $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                            $(this).toggleClass('open');
                        }
                    );
                });
            </script>
            <div class="col-md-4 search-agileinfo">
                <form class="@Url.Action("Index", "Search")">

                    <input type="search" name="Search" placeholder="Search for a Product..." required="">
                    <button type="submit" class="btn btn-default search" aria-label="Left Align" formaction="@Url.Action("Index", "Search")" Search>
                        <i class="fa fa-search" aria-hidden="true"> </i>
                    </button>


                </form>

            </div>
            <div class="col-md-1 cart-wthree">
                <div class="cart">
                    <form action="@Url.Action("Index","GioHangs")" method="post" >
                        <input type="hidden" name="cmd" value="_cart" />
                        <input type="hidden" name="display" value="1" />
                        <button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
                    </form>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="footer">
                <div class="container">
                    <div class="sliderfig">
                        <ul id="flexiselDemo1">
                            <li>
                                <img sizes="15" src="~/images/LGNike.png" alt=" " class="img-responsive" />
                            </li>
                            <li>
                                <img sizes="15" src="~/images/LGPuma.png" alt=" " class="img-responsive" />
                            </li>
                            <li>
                                <img sizes="15" src="~/images/new Balance.jpg" alt=" " class="img-responsive" />
                            </li>

                            <li>
                                <img sizes="15" src="~/images/Jordan.jpg" alt=" " class="img-responsive" />
                            </li>
                            <li>
                                <img sizes="15" src="~/images/Supreme.jpg" alt=" " class="img-responsive" />
                            </li>
                            <li>
                                <img sizes="15" src="~/images/LGAdi.jpg" alt=" " class="img-responsive" />
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-grids fgd1">
                        <a href="~/Home">
                            <h3>
                                MEOMUN
                                <span>SHOP</span>
                            </h3>
                        </a>
                        <ul>
                            <li>80/68 Dương Quảng Hàm, P. 5, Q. Gò Vấp,</li>
                            <li>Tp. Hồ Chí Minh.</li>
                            <li><a href="mailto:info@example.com">info@example.com</a></li>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                            <a href="#"><i class="fa fa-mobile" aria-hidden="true"></i></a>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-grids fgd3">
                        <h4>Khách hàng</h4>
                        <ul>

                            <li><a href="login.html">Đăng nhập</a></li>
                            <li><a href="register.html">Đăng ký</a></li>
                            <li><a href="payment.html">Giỏ hàng</a></li>

                        </ul>
                    </div>
                    <div class="col-md-3 footer-grids fgd4">
                        <h4>Thông tin và đánh giá</h4>
                        <ul>

                            <li><a>Thông tin</a></li>
                            <li><a href="recommended.html">Đánh giá </a></li>

                        </ul>
                    </div>
                    <p>&copy; @DateTime.Now.Year MEOMUN TEAM . All rights reserved | Design by - MEOMUN TEAM </p>
                </div>
            </div>
        </footer>

    </div>
</body>
</html>